#!/bin/bash -e

TARGET_DIR="$BUILT_PRODUCTS_DIR/CarthageKitTests.xctest/Contents/Resources"

cp -R Tests/CarthageKitTests/Resources/* "$TARGET_DIR"
cp Tests/CarthageKitTests/fixtures/CartfilePrivateOnly.zip "$TARGET_DIR"
script/copy-fixtures "$TARGET_DIR"
