#!/bin/bash
#
# Copies fixture projects into the test bundle directly, so they don't have to
# be added to the Carthage workspace. This avoids confusing Xcode with
# "subprojects" that are actually just originating from a fixture.

if [[ -z $1 ]]; then
    echo "Error: You must pass a destination directory."
    exit 1
fi

current=$(cd "$(dirname $0)" && pwd)
destination="$1"

for fixture_zip in $(cd "$current/../Tests/CarthageKitTests/fixtures" && ls *.zip)
do
    fixture=${fixture_zip%.zip}
    rm -Rf "$destination/__MACOSX"
    rm -Rf "$destination/$fixture"
    unzip -q -d "$destination" "$current/../Tests/CarthageKitTests/fixtures/$fixture"
done

