#!/bin/bash -x

SOURCE_DIR="Tests/CarthageKitTests/Resources"
TARGET_DIR="$BUILT_PRODUCTS_DIR/CarthageKitTests.xctest/Contents/Resources"

mkdir -p "$TARGET_DIR"

cp -R "$SOURCE_DIR"/* "$TARGET_DIR"

