#!/bin/bash -e

TARGET_DIR="$1/Contents/Resources"

mkdir -p "$TARGET_DIR"
cp -R Tests/CarthageKitTests/Resources/* "$TARGET_DIR"
cp Tests/CarthageKitTests/fixtures/CartfilePrivateOnly.zip "$TARGET_DIR"
script/copy-fixtures "$TARGET_DIR"
